### PR TITLE
Fix filenames truncated by `maxLength` not keeping their extension

### LINKED ISSUE #13: File names truncated by `maxLength` should keep their extension
```js
const unsafeName = "This? This is very long filename that will lose its extension when passed into filenamify, which could cause issues.csv";
const safeName = filenamify(unsafeName);
console.log(safeName); // "This! This is very long filename that will lose its extension when passed into filenamify, which cou" (length: 100)
// Ideal: "This! This is very long filename that will lose its extension when passed into filenamify, which.csv" (length: 100)
```

Perhaps this could be an option `keepExtension`, default to `false` to keep backwards compatibility.

### PR DESCRIPTION
**Pull request by aakriti-kedia**
Fixes #13 

Excludes the extension, truncates the string to the required length, appends the extension.

Example - 
**Input :** very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_long_filename.txt

**Output**
very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_.txt

### CODE REVIEW

File: filenamify.js [hunk 1]
```diff
@@ -31,7 +31,11 @@ export default function filenamify(string, options = {}) {
 	}
 
 	string = filenameReservedRegex.windowsNames().test(string) ? string + replacement : string;
-	string = string.slice(0, typeof options.maxLength === 'number' ? options.maxLength : MAX_FILENAME_LENGTH);
+	const allowedLength = typeof options.maxLength === 'number' ? options.maxLength : MAX_FILENAME_LENGTH;
+	if (allowedLength < string.length) {
```
Comment (sindresorhus) [inline filenamify.js:35]: I think it reads better if `string.length` comes first in this conditional.

**Comment by aakriti-kedia** [comment]
Hi @sindresorhus 
My thought process was that if this code is part of filenamify instead of filenamify-path, all the processing related to filename would be dealt in filenamify and abstracted from filenamify-path. As per the logic - If the filename is long, we wish to truncate the filename and not its path - as this is an operation on the filename, it would make sense if it resides in filenamify. 

Please feel free to let me know if you have any concerns with extending this approach to filenamify and not keeping it restricted to filenamify-path.

**Comment by papb** [comment]
Maybe this could be updated to also account for a few specific "double" extensions such as `.tar.gz` and `.tar.bz2`?

**Comment by sindresorhus** [comment]
@papb I don't think it makes sense to handle such extension automatically. That would be surprising behavior. Maybe there could be an option to define a set of known double extensions or something. It's not something I need, so if you need it, open an issue with a proper proposal.
